# Generated by Django 5.1.6 on 2025-04-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_description_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(blank=True, max_length=555, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='main_produc_categor_9c4415_idx'),
        ),
    ]
