# Generated by Django 5.1.6 on 2025-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
