# Generated by Django 5.1.6 on 2025-05-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
