# Generated by Django 5.1.6 on 2025-05-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_story_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
