# Generated by Django 5.1.6 on 2025-05-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productattribute_productattributevalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Атрибут продукта', 'verbose_name_plural': 'Атрибуты продуков'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'Значение атрибута продукта', 'verbose_name_plural': 'Значения атрибутов продукта'},
        ),
    ]
